[package]
name = "scrapster"
version = "0.1.5"
edition = "2024"

[lib]
name = "scrapster"
crate-type = ["rlib", "cdylib"]

[dependencies]
glob = "0.3.3"
tokio = { version = "1.48.0", features = ["full"] }
pyo3 = { version = "0.22.6", features = ["extension-module", "abi3-py38"] }
